/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Game = { 'freeFire' : null } |
  { 'brCs' : null };
export type Mode = { 'loneWolf' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Status = { 'closed' : null } |
  { 'full' : null } |
  { 'open' : null };
export type Timestamp = bigint;
export interface Tournament {
  'id' : bigint,
  'map' : string,
  'status' : Status,
  'game' : Game,
  'mode' : Mode,
  'name' : string,
  'createdAt' : Timestamp,
  'creatorName' : string,
  'roomPassword' : string,
  'players' : Array<string>,
  'currentPlayers' : bigint,
  'entryFee' : bigint,
  'roomId' : string,
  'maxPlayers' : bigint,
}
export interface TournamentInput {
  'map' : string,
  'game' : Game,
  'mode' : Mode,
  'name' : string,
  'creatorName' : string,
  'roomPassword' : string,
  'entryFee' : bigint,
  'roomId' : string,
  'maxPlayers' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTournament' : ActorMethod<[TournamentInput], Tournament>,
  'deleteTournament' : ActorMethod<[bigint, string], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[bigint, string], Tournament>,
  'listTournaments' : ActorMethod<[], Array<Tournament>>,
  'schema' : ActorMethod<[], string>,
  'updateTournament' : ActorMethod<
    [bigint, string, TournamentInput],
    Tournament
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];