/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Game = IDL.Variant({ 'freeFire' : IDL.Null, 'brCs' : IDL.Null });
export const Mode = IDL.Variant({ 'loneWolf' : IDL.Null });
export const TournamentInput = IDL.Record({
  'map' : IDL.Text,
  'game' : Game,
  'mode' : Mode,
  'name' : IDL.Text,
  'creatorName' : IDL.Text,
  'roomPassword' : IDL.Text,
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Text,
  'maxPlayers' : IDL.Nat,
});
export const Status = IDL.Variant({
  'closed' : IDL.Null,
  'full' : IDL.Null,
  'open' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'map' : IDL.Text,
  'status' : Status,
  'game' : Game,
  'mode' : Mode,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'creatorName' : IDL.Text,
  'roomPassword' : IDL.Text,
  'players' : IDL.Vec(IDL.Text),
  'currentPlayers' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Text,
  'maxPlayers' : IDL.Nat,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTournament' : IDL.Func([TournamentInput], [Tournament], []),
  'deleteTournament' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat, IDL.Text], [Tournament], []),
  'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateTournament' : IDL.Func(
      [IDL.Nat, IDL.Text, TournamentInput],
      [Tournament],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Game = IDL.Variant({ 'freeFire' : IDL.Null, 'brCs' : IDL.Null });
  const Mode = IDL.Variant({ 'loneWolf' : IDL.Null });
  const TournamentInput = IDL.Record({
    'map' : IDL.Text,
    'game' : Game,
    'mode' : Mode,
    'name' : IDL.Text,
    'creatorName' : IDL.Text,
    'roomPassword' : IDL.Text,
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Text,
    'maxPlayers' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'closed' : IDL.Null,
    'full' : IDL.Null,
    'open' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'map' : IDL.Text,
    'status' : Status,
    'game' : Game,
    'mode' : Mode,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'creatorName' : IDL.Text,
    'roomPassword' : IDL.Text,
    'players' : IDL.Vec(IDL.Text),
    'currentPlayers' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Text,
    'maxPlayers' : IDL.Nat,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTournament' : IDL.Func([TournamentInput], [Tournament], []),
    'deleteTournament' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat, IDL.Text], [Tournament], []),
    'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateTournament' : IDL.Func(
        [IDL.Nat, IDL.Text, TournamentInput],
        [Tournament],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };